import MobileMenu from "@/components/MobileMenu";
import Playerbar from "@/components/Playerbar";
import Sidebar from "@/components/Sidebar";
import Provider from "@/provider/Provider";
import "@/styles/globals.css";
import { Nunito } from "next/font/google";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Marvinel | Spotify Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} bg-black text-white overflow-hidden`}
      >
        <Provider session={session}>
          <main className="h-full w-full flex">
            <Sidebar />
            <MobileMenu />
            {children}
            <Playerbar />
          </main>
        </Provider>
      </body>
    </html>
  );
}
